site_name: 'conda-env-manager: cenv'
nav:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Usage: usage.md
    - About: about.md
    - License: license.md
    - Impressum: impressum.md
theme:
    name: readthedocs
    hljs_languages:
        - yaml
